version: "3.8"

services:
  serenity-sdk-python:
    init: true
    privileged: true
    image: cloudwalldev.azurecr.io/cloudwallcapital/devcontainer/serenity.deploy:latest
    command: /bin/sh -c "while sleep 1000; do :; done"
    entrypoint: /usr/local/share/docker-init.sh
    network_mode: host
    volumes:
      - type: bind
        source: /workdrive/dev/serenity.sdk.python
        target: /workspaces/serenity.sdk.python
      - type: volume
        source: home-data
        target: /home/serenitydev
      - type: bind
        source: /home/serenitydev/.azure
        target: /home/serenitydev/.azure
volumes:
  docker-data:
  home-data:
